const STATUS_OK_CREATED = 201;
const STATUS_ERROR_CREATE = 400;
const STATUS_OK = 200;
const STATUS_ERROR_NOTFOUND = 404;

module.exports = {
  STATUS_OK_CREATED,
  STATUS_ERROR_CREATE,
  STATUS_OK,
  STATUS_ERROR_NOTFOUND
}